/**
 * STORE_ENGINE - Controller
 */
import { chatJson } from "@/core/ai";
import { getProjectPath } from "@/core/storage";
import { writeFiles } from "@/core/storage";

const SYSTEM = `Generate eCommerce store structure as JSON:
{
  "store_name": "string",
  "products": [{"id":"1","name":"","price":0,"description":"","image_prompt":""}],
  "currency": "USD"
}
Return ONLY valid JSON.`;

export async function generate(input: {
  prompt: string;
  userId: string;
  language?: string;
}): Promise<{ ok: boolean; projectId?: string; previewUrl?: string; error?: string }> {
  try {
    const raw = await chatJson<{ store_name: string; products: Array<{ id: string; name: string; price: number; description: string; image_prompt: string }>; currency: string }>(SYSTEM, `Create store: ${input.prompt}`);
    const projectId = `store_${Date.now()}`;
    const projectPath = getProjectPath("stores", projectId);

    const products = raw.products || [{ id: "1", name: "Product 1", price: 29, description: "Description", image_prompt: "product" }];
    const storeName = raw.store_name || "Store";

    const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${storeName}</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="bg-slate-900 text-white p-6">
<h1 class="text-3xl font-bold mb-6">${storeName}</h1>
<div class="grid md:grid-cols-3 gap-4" id="products">${products.map(p => `
<div class="border border-white/10 rounded-lg p-4">
  <img src="https://source.unsplash.com/featured/400x400?${encodeURIComponent(p.image_prompt || "product")}" alt="${p.name}" class="w-full h-48 object-cover rounded"/>
  <h3 class="font-bold mt-2">${p.name}</h3>
  <p class="text-slate-400 text-sm">${p.description}</p>
  <p class="text-indigo-400 font-bold">$${p.price}</p>
  <button onclick="addToCart('${p.id}')" class="mt-2 w-full py-2 bg-indigo-600 rounded">Add to Cart</button>
</div>`).join("")}</div>
<div id="cart" class="mt-8 p-4 border border-white/10 rounded-lg hidden">
  <h2>Cart</h2>
  <div id="cart-items"></div>
  <button onclick="checkout()" class="mt-4 py-2 px-4 bg-green-600 rounded">Checkout</button>
</div>
<script>
const cart={};
function addToCart(id){cart[id]=(cart[id]||0)+1;document.getElementById('cart').classList.remove('hidden');updateCart();}
function updateCart(){document.getElementById('cart-items').innerHTML=Object.entries(cart).map(([k,v])=>k+': '+v).join(', ');}
function checkout(){alert('Checkout - Stripe integration template');}
</script>
</body>
</html>`;

    writeFiles(projectPath, [
      { path: "index.html", content: html },
      { path: "products.json", content: JSON.stringify({ products, currency: raw.currency || "USD" }, null, 2) },
      { path: "README.md", content: `# ${storeName}\n\nGenerated by FERDOUS AI OS` },
    ]);

    return { ok: true, projectId, previewUrl: `/generated/stores/${projectId}/index.html` };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "Generation failed" };
  }
}
