/**
 * FERDOUS AI OS - Website Tool File Generator
 * Writes real project files to generated-projects/{projectId}/
 */
const fs = require("fs");
const path = require("path");
const { GENERATED_DIR } = require("../../../config/paths");
const renderer = require("./renderer");

function generate(projectId, output, options = {}) {
  const { html, css, js } = renderer.render(output);
  const projectPath = path.join(GENERATED_DIR, projectId);

  if (!fs.existsSync(projectPath)) {
    fs.mkdirSync(projectPath, { recursive: true });
  }

  fs.writeFileSync(path.join(projectPath, "index.html"), html, "utf8");
  fs.writeFileSync(path.join(projectPath, "styles.css"), css, "utf8");
  fs.writeFileSync(path.join(projectPath, "script.js"), js, "utf8");

  const packageJson = {
    name: "ferdous-generated-" + projectId,
    version: "1.0.0",
    description: "Generated by FERDOUS AI OS",
    private: true
  };
  fs.writeFileSync(path.join(projectPath, "package.json"), JSON.stringify(packageJson, null, 2));

  const readme = `# Generated by FERDOUS AI OS\n\nProject ID: ${projectId}\n\nOpen index.html in a browser or deploy to any static host.`;
  fs.writeFileSync(path.join(projectPath, "README.md"), readme);

  return {
    projectId,
    path: projectPath,
    files: ["index.html", "styles.css", "script.js", "package.json", "README.md"],
    previewUrl: `/generated/${projectId}/index.html`
  };
}

module.exports = {
  generate
};
